### ISSUE TITLE
Choix du sujet en ML python

### ISSUE THREAD

**Issue by Thibaud-Meynier** [JeffAbrahamson/IAE-ann-svm#1]
Voici le sujet que nous avons choisis avec Yasmina Amdjahdi 

Real or Not? NLP with Disaster Tweets https://www.kaggle.com/c/nlp-getting-started

**Comment by JeffAbrahamson** [comment]
Pourriez-vous partager le lien vers votre repo svp ?

**Comment by Thibaud-Meynier** [comment]
https://github.com/Thibaud-Meynier/M2-EKAP

**Comment by JeffAbrahamson** [comment]
Merci !

**Comment by Thibaud-Meynier** [comment]
Le dossier finale d'évaluation avec le rapport écrit en pdf et le notebook jupyter avec les codes ayant permis d'obtenir nos résultats est dans le repo https://github.com/Thibaud-Meynier/M2-EKAP.
