### ISSUE TITLE
Communication de l'achèvement du projet ANN-SVM Marina Gourin et Julie Perron

### ISSUE THREAD

**Issue by Julie-Perron** [JeffAbrahamson/IAE-ann-svm#11]
Bonsoir,

Nous vous informons que nous avons achevé notre projet pour l'évaluation de la matière Big Data sous Python (ANN-SVM).
Vous trouverez dans notre repo tous les éléments demandés.

Nous avons choisi le sujet Kaggle suivant : Contradictory, My Dear Watson. 

[Lien Kaggle](https://www.kaggle.com/c/contradictory-my-dear-watson)
[Lien Repo](https://github.com/Julie-Perron/Projet-ANN-SVN-MarinaGourin-JuliePerron)

Bien cordialement.

Équipe : Marina Gourin et Julie Perron

**Comment by JeffAbrahamson** [comment]
Visiblement vous ne laissez rien au hasard !  ;-)
