### ISSUE TITLE
MAILLARD Amaury & FATTORELLI Vincent : Cassava Leaf Disease Classification

### ISSUE THREAD

**Issue by AmauMaill** [JeffAbrahamson/IAE-ann-svm#15]
# Kaggle
https://www.kaggle.com/c/cassava-leaf-disease-classification/overview/description
# Repo
https://github.com/AmauMaill/Cassava-Leaf-Disease-Classification.git

**Comment by JeffAbrahamson** [comment]
Pourriez-vous ajouter vos noms dans le README svp ?
