### ISSUE TITLE
Projet de SVM & ANN - KOUYATE & SIABI

### ISSUE THREAD

**Issue by Achille1** [JeffAbrahamson/IAE-ann-svm#20]
Projet de KOUYATE & SIABI

**Kaggle**: https://www.kaggle.com/c/chaii-hindi-and-tamil-question-answering

**Repository**: https://github.com/Achille1/Projet_M2_Chaii-Hindi_and_Tamil_Question_Answering

**Comment by JeffAbrahamson** [comment]
Pourriez-vous ajouter vos noms au README.md svp ?
Merci.
