### ISSUE TITLE
Projet M2 EKAP : Achèvement du projet Brain Tumor Radiogenomic Classification - LE MEE Luc et PETITEAU Antoine

### ISSUE THREAD

**Issue by AntoinePetiteau** [JeffAbrahamson/IAE-ann-svm#23]
Bonjour, 

Nous vous confirmons l'achèvement de notre projet. 

Voici notre rapport en format pdf : [Rapport_Kaggle_PETITEAU_LEMEE_M2EKAP.pdf](https://github.com/JeffAbrahamson/IAE-ann-svm/files/7565818/Rapport_Kaggle_PETITEAU_LEMEE_M2EKAP.pdf)
Le code quant à lui se trouve sur notre repository : https://github.com/AntoinePetiteau/Brain-Tumor-Radiogenomic-Classification

LE MEE Luc et PETITEAU Antoine

**Comment by JeffAbrahamson** [comment]
Top, merci !

**Comment by JeffAbrahamson** [comment]
Juste pour préciser, mon attente est que je trouve le rapport et votre code dans votre [repo](https://github.com/AntoinePetiteau/Brain-Tumor-Radiogenomic-Classification).  Je note ici simplement que vous l'avez terminé.

**Comment by AntoinePetiteau** [comment]
Le repo contient à la fois le code et le rapport justement, mais j'ai rajouté le rapport dans l'issue, au cas où.
