### ISSUE TITLE
[FINI] Cassava Leaf Disease Classification - Amaury Maillard & Vincent Fattorelli

### ISSUE THREAD

**Issue by AmauMaill** [JeffAbrahamson/IAE-ann-svm#26]
Bonsoir,

Voici le rendu de notre projet :

* [Repository](https://github.com/AmauMaill/Cassava-Leaf-Disease-Classification)
* [Rapport](https://github.com/AmauMaill/Cassava-Leaf-Disease-Classification/blob/main/report_svm_ann_maillard_fattorelli.pdf)
* [Code](https://github.com/AmauMaill/Cassava-Leaf-Disease-Classification/blob/main/report-svm-ann-maillard-fattorelli.ipynb)

Amaury Maillard & Vincent Fattorelli

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet.  Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
