### ISSUE TITLE
Projet Jane Street Market Prediction terminé, ROMAND Kyllien & DEL'CHATEAU Jeaan-Baptiste

### ISSUE THREAD

**Issue by Delchateaujb** [JeffAbrahamson/IAE-ann-svm#27]
Bonsoir Monsieur,

Veuillez trouver ci joint 

Notre rapport du projet : https://github.com/Kyllien/Jane-Street-Market-Prediction/blob/cbe9d8145d8d75c874d29c911ca5faaaf2b6ecda/Kyllien%20&%20Jean-Baptiste%20projet.pdf

Notre code du projet : https://github.com/Kyllien/Jane-Street-Market-Prediction.git

ROMAND Kyllien & DEL'CHATEAU Jean-Baptiste

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet.  Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
