### ISSUE TITLE
Projet Andre et Sory: Predict Futures Sales

### ISSUE THREAD

**Issue by AndreAng1** [JeffAbrahamson/IAE-ann-svm#28]
Bonjour Monsieur. 
Ci-joint les liens de notre projet.

Rapport: 
https://github.com/AndreAng1/SVM-ANN-Andre-M2-EKAP/blob/main/Projet_predict_futures_sales.pdf

Notebook: 
https://github.com/AndreAng1/SVM-ANN-Andre-M2-EKAP/blob/main/Predict_Futures_Sales_Andre_Sory.ipynb

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet.  Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
