### ISSUE TITLE
Projet final G2Net-Gravitational-Wave-Detection VALICON Astrid et LAGRE Gabin

### ISSUE THREAD

**Issue by astridval** [JeffAbrahamson/IAE-ann-svm#29]
Bonjour, 

Voici notre projet sous format PDF, ainsi que le code sous Python. 

- https://github.com/astridval/G2Net-Gravitational-Wave-Detection/blob/de0abb74f83d2ae589bccea7f882c718d03b667e/SVM%20et%20RDN_VALICON_Astrid_LAGRE_Gabin.pdf 

- https://github.com/astridval/G2Net-Gravitational-Wave-Detection/blob/de0abb74f83d2ae589bccea7f882c718d03b667e/Projet_Kaggle_LAGRE_Gabin_VALICON_Astrid.py

Astrid VALICON et Gabin LAGRE

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet.  Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
