### ISSUE TITLE
Rendu du projet final SVM - LearnPlatform COVID-19 Impact on Digital Learning - Louis Mortreuil et Sara Meziani

### ISSUE THREAD

**Issue by Sara-Louis** [JeffAbrahamson/IAE-ann-svm#30]
Bonjour,

Voici notre projet sous format PDF, ainsi que le code sous Python.

Document pdf :  https://github.com/Sara-Louis/Sara-Meziani-et-Louis-Mortreuil/blob/main/Projet-SVM_Final-MEZIANI-SARA_-MORTEUIL-LOUIS.pdf

Code python : https://github.com/Sara-Louis/Sara-Meziani-et-Louis-Mortreuil/blob/main/Projet_SVM_Final-Louis_Mortreuil_Sara_Meziani.ipynb

Louis et Sara

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet.  Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
