### ISSUE TITLE
Projet M2 EKAP: Google Brain - Ventilator Pressure Prediction - Mocher Vrignaud 

### ISSUE THREAD

**Issue by LucieVrignaud** [JeffAbrahamson/IAE-ann-svm#31]
Membre de l'équipe : Cécile Mocher Lucie Vrignaud

Compétition Kaggle : https://www.kaggle.com/c/ventilator-pressure-prediction/overview

Repository : https://github.com/LucieVrignaud/Projet-M2-EKAP-Mocher-Vrignaud.git

Bonjour,
Nous avons terminé notre rapport et notre code que vous trouverez dans notre repo ci-dessus.

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet. Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
