### ISSUE TITLE
Projet M2 EKAP : Wikipedia - Image/Caption Matching - CHIFFOLEAU - CORVEN

### ISSUE THREAD

**Issue by QuentinChiff** [JeffAbrahamson/IAE-ann-svm#32]
Membre de l'équipe : Quentin Chiffoleau et Loic Corven

Compétition Kaggle : https://www.kaggle.com/c/wikipedia-image-caption/overview/timeline

Repository : https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN.git

Bonjour,
Comme convenu avec vous en cours, nous postons notre rapport et notre code que vous trouverez dans notre repo ci-dessus, cependant ceux-ci ne sont pas définitifs et sont amenés à changer d'ici ce week-end.
Merci d'avance

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet. Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).

**Comment by JeffAbrahamson** [comment]
et : pas de soucis
