### ISSUE TITLE
Projet final _ chaii - Hindi and Tamil Question Answering _ Mohamed KOUYATE et Achille SIABI

### ISSUE THREAD

**Issue by Achille1** [JeffAbrahamson/IAE-ann-svm#33]
Bonjour,

Ci-dessous les documents relatifs à notre projet en SVM&ANN:

- [Kaggle](https://www.kaggle.com/c/chaii-hindi-and-tamil-question-answering)

- [Rapport](https://github.com/Achille1/Projet_M2_Chaii-Hindi_and_Tamil_Question_Answering/blob/main/Rapport_SVM%26ANN_KOUYATE_SIABI.pdf)

- [Notebook](https://github.com/Achille1/Projet_M2_Chaii-Hindi_and_Tamil_Question_Answering/blob/main/Notebook_final_SVM%26ANN_KOUYATE_SIABI.ipynb)

- [Repository](https://github.com/Achille1/Projet_M2_Chaii-Hindi_and_Tamil_Question_Answering)

**Mohamed KOUYATE & Achille SIABI**

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet. Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
