### ISSUE TITLE
Projet final : Wikipedia - Image/Caption Matching CORVEN loïc CHIFFOLEAU quentin 

### ISSUE THREAD

**Issue by lcorven** [JeffAbrahamson/IAE-ann-svm#34]
Vous trouverez ci-joint dossier fini.

Le Repository : 

[Repository](https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN)

Ce dernier comporte 4 documents :

[Script analyse descriptive](https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN/blob/main/Analyse%20descriptive%20des%20donn%C3%A9es%20.ipynb)

[Modèle par CNN](https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN/blob/main/Mod%C3%A8le%20par%20CNN(1).ipynb)

[Modèle de prévision par URL](https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN/blob/main/Mod%C3%A8le%20pr%C3%A9vision%20par%20URL(2).ipynb)

[Rapport_PDF](https://github.com/lcorven/PROJET_M2_EKAP_CHIFFOLEAU_CORVEN/blob/main/Dossier%20SVM%20CHIFFOLEAU%20CORVEN.docx.pdf)

La base de données : 

[Données](https://www.kaggle.com/c/wikipedia-image-caption/data)

**Comment by JeffAbrahamson** [comment]
Merci.

Pour être précis, je note ici l'achèvement du projet. Lors de l'évaluation, je m'attends à ce que je trouve ce qu'il faut dans votre repo (éventuellement, expliqué en README.md si ce n'est pas autrement évident).
