### ISSUE TITLE
Choix du sujet Kaggle pour le cours ANN SVM (Marina Gourin et Julie Perron)

### ISSUE THREAD

**Issue by Julie-Perron** [JeffAbrahamson/IAE-ann-svm#4]
Équipe : Marina Gourin et Julie Perron
Nous avons choisi le sujet Kaggle suivant : Contradictory, My Dear Watson. 

[Lien Kaggle](https://www.kaggle.com/c/contradictory-my-dear-watson)

[Lien Repo](https://github.com/Julie-Perron/Projet-ANN-SVN-MarinaGourin-JuliePerron)

**Comment by JeffAbrahamson** [comment]
Bon usage de markup !
