### ISSUE TITLE
Projet python Naoufali Madi et Darlene Nibogora 

### ISSUE THREAD

**Issue by Naoufali976** [JeffAbrahamson/IAE-ann-svm#6]
Bonjour Monsieur,
Voici notre sujet pour le projet de Big Data sous Python :

**Preditc Future Sales** :https://www.kaggle.com/c/competitive-data-science-predict-future-sales?fbclid=IwAR1RvGM1yToxXBsvXxWx_Fw1IoYtAqRGhhU7ORhzm8-yEZJwl2iMC7zkpXo

**Comment by JeffAbrahamson** [comment]
* Qui est la deuxième personne ?
* Pourriez-vous partager le lien vers votre repo svp ?

**Comment by Naoufali976** [comment]
Bonjour, 
Le voici :https://github.com/Naoufali976/Big_data_python_svm/blob/main/README.md

**Comment by JeffAbrahamson** [comment]
Merci !
