### ISSUE TITLE
Repo Diane Teodoro Riwan

### ISSUE THREAD

**Issue by teodoromouniertebas** [JeffAbrahamson/IAE-ann-svm#9]
Here is the repository for the ML class in Master 2 EKAP: 
Authors: Thierry Diane
               Mounier Tebas Teodoro
               Perron Riwan
[https://github.com/teodoromouniertebas/TitanicDianeTeodoroRiwan](url)

**Comment by JeffAbrahamson** [comment]
Vous avez choisis le projet d'apprentissage, qui reste ouvert en perpétuité afin de montrer comment interagir avec Kaggle.  J'accepte que vous le fassiez, mais sachez qu'il y a autant d'exemple et de blogs sur ce projet que mes attentes seraient légèrement élevées.

Dites-moi si vous maintenez ce projet.

**Comment by teodoromouniertebas** [comment]
Bien, nous n'avions pas vu que le projet était ouvert en perpétuité, seulement qu'il paraissait très intéressant. Cependant,  nous préferons changer de sujet et tenter des algorithmes plus évolués (avec plus de recherche) et travaillerons donc sur le sujet suivant concernant le transfert de style d'images vers des peintures du style de Monet (par le biais des modèles GAN). Nous changerons le nom du repo d'ici la fin de la semaine. 
[https://www.kaggle.com/c/gan-getting-started/overview](url)

**Comment by DianeThy** [comment]
Bonjour, 
Après réflexion nous décidons finalement de traiter le sujet "Digit Recognizer" disponible au lien suivant [https://www.kaggle.com/c/digit-recognizer/overview](url). 
Notre repo est lui, disponible ici : [https://github.com/teodoromouniertebas/KaggleDianeTeodoroRiwan.git](url)

**Comment by JeffAbrahamson** [comment]
ok, merci, c'est noté.
